### ISSUE TITLE
Add comport white list

### ISSUE THREAD

**Issue by zegreatclan** [zegreatclan/AssettoCorsaTools#108]
Is it possible for you to implement beside the blacklist for COM Ports an alternative whitelist?
The blacklist works really well. The problem is, sometimes when you plug in a new device and forget to make the entry it cause problems. Would be nice to have the choise to use white- or blacklist.

Resquested by @Gallow24

**Comment by redion1992** [comment]
Along these lines, it would be good to move the blacklist/whitelist out of SimHubWPF.exe.config if possible, as this gets overwritten by the setup with each update.
