### ISSUE TITLE
Dash Studio formatting issue

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#110]
When adding a symbol at the end of binding in dash studio it sometimes makes the value go crazy. See pictures:
![screenshot_3](https://user-images.githubusercontent.com/29677438/27517628-890d66b2-59c7-11e7-8ea6-1f7e6c7e37a1.png)
![screenshot_4](https://user-images.githubusercontent.com/29677438/27517629-890e71f6-59c7-11e7-9dcf-05a641d64efe.png)

**Comment by zegreatclan** [comment]
it's a bug and it's not at the same time it's how data is represented in .net I can't do something about this :(, you have to format the value to round it
