### ISSUE TITLE
Possibly add more data for RFactor 2

### ISSUE THREAD

**Issue by Sylvesta** [zegreatclan/AssettoCorsaTools#122]
Current data being exported for RF2 is very limited compared to other games ie AC.

Please look into getting the data.

**Comment by zegreatclan** [comment]
Yeah ! I agree, not the worst game nonetheless, but could be better, I'll look to make my own plugin since I have a pretty decent base with the Crewchief one. But it will take time.

**Comment by Sylvesta** [comment]
That would be great!! 

Thought I would drop this here as a record and doesn't get lost lol.
