### ISSUE TITLE
Data that can become 'newdata'

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#123]
Air temp
Assetto: [DataCorePlugin.GameRawData.Physics.AirTemp]
Pcars: [DataCorePlugin.GameRawData.mAmbientTemperature]
IRacing: [DataCorePlugin.GameRawData.SessionData.WeekendInfo.TrackAirTemp]
RFactor 2: [DataCorePlugin.GameRawData.Data.mAmbientTemp]

Track temp
Assetto: [DataCorePlugin.GameRawData.Physics.RoadTemp] 
Pcars: [DataCorePlugin.GameRawData.mTrackTemperature]
IRacing: [DataCorePlugin.GameRawData.SessionData.WeekendInfo.TrackSurfaceTemp]
RFactor 2: [DataCorePlugin.GameRawData.Data.mTrackTemp]

Those are the games I checked :)

**Comment by zegreatclan** [comment]
Nice ! Thanks !
