### ISSUE TITLE
Ability to make a dial gauge go through 360 degrees

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#124]
So we can create analogue clocks! :)

**Comment by zegreatclan** [comment]
I clean old requests :D 

In fact "modulo" in ncalc is the way to go 

6%60 = 6
66%60 = 6
120%60 = 0

And on the other side by using the custom lable you can properly loop the dial : 
![image](https://user-images.githubusercontent.com/2207331/34460426-ef983ca6-ee0d-11e7-8a4c-700c9a160c05.png)
