### ISSUE TITLE
AC - PCars Cross Compatibility - Tyre Wear

### ISSUE THREAD

**Issue by PuReAdDicT** [zegreatclan/AssettoCorsaTools#140]
Both have max 100 ok
AC has range only 90-100
PCars has range 1-100

**Comment by zegreatclan** [comment]
It will be possible to adjust minimum tyre wear for any game default for Ac will give something close to PCars1/2 : 
![image](https://user-images.githubusercontent.com/2207331/42294819-6f307844-7fe4-11e8-91c2-a666b9552af2.png)
