### ISSUE TITLE
cross compatable data

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#141]
Another one for a 'newdata' label. Track Length:

Assetto: DataCorePlugin.GameRawData.Track.TrackInfo.length
PCars: DataCorePlugin.GameRawData.mTrackLength
Iracing: DataCorePlugin.GameRawData.SessionData.WeekendInfo.TrackLength (not shown in metres, is shown in km)
Raceroom: DataCorePlugin.GameRawData.LayoutLength (Not sure if metres)
Codemasters: DataCorePlugin.GameRawData.TrackLength (again not sure if metres)
Rfactor has: DataCorePlugin.GameRawData.CurrentPlayer.mTrackEdge But assume that's not length. Haven't checked.

**Comment by zegreatclan** [comment]
I checked, I did it a while ago, only iracing was missing, but it's fixed now ;)
