### ISSUE TITLE
Ability to have pre-sets

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#143]
Not sure if this is possible. But what if you could record some presets and they interact with the game. For example record a couple of brake bias settings and use buttons to recall that position.

Like I said I'm not sure if it's even possible to interact with games like this but just putting the idea out there! :)

**Comment by zegreatclan** [comment]
I'm afraid this is not possible ;) Except in very secured conditions known computer/setup/inputs these things are almost impossible.
