### ISSUE TITLE
Dash studio web version issue

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#144]
Hi,

Not sure if you are aware but on dash studio the background colours and images aren't working on linear gauges when running in web mode.

**Comment by zegreatclan** [comment]
Images done :D for the color for me it's working , do you have a sample ?

**Comment by Meekstaaa** [comment]
My Ferrari f40 dash has missing backgrounds on some of the warning lights.

Many thanks

David Meek
Sent from my iPhone

On 8 Aug 2017, at 20:00, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Images done :D for the color for me it's working , do you have a sample ?

**Comment by zegreatclan** [comment]
Hum ! Sorry for the long delay ! 

OK found it : Unsupported component type : SimHub.Plugins.OutputPlugins.GraphicalDash.Models.CircularGaugeItem, SimHub.Plugins

Still some components missing :D,i'll look
