### ISSUE TITLE
TC & ABS Value property issues

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#145]
Hey,

Found an issue with the ABS and TC level ncalcs.

Basically its an issue when the in game scale is different. Some cars have only 6 tc values or could have 16. It produces weird values depending on the scale.

Not sure if there is a way around it.

**Comment by zegreatclan** [comment]
Sadly it's not the level but the % of the TC and ABS so for instance
level 1 is 12%
level 2 is 16%
level 12 is 20% ...

And you get the 20%
Sadly i can't circumvent this, the only place where the correspondance table are available is in encrypted files.

**Comment by Meekstaaa** [comment]
Damn I thought you might say that :(

Oh well! 👍

Many thanks

David Meek
Sent from my iPhone

On 22 Aug 2017, at 15:59, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Sadly it's not the level but the % of the TC and ABS so for instance
level 1 is 12%
level 2 is 16%
level 12 is 20% ...

And you get the 20%
Sadly i can't circumvent this, the only place where the correspondance table are available is in encrypted files.
