### ISSUE TITLE
Arduino not detected by SimHub

### ISSUE THREAD

**Issue by ShootingTiger** [zegreatclan/AssettoCorsaTools#153]
Hey Guys,

I'm really new in this topic, but I've dont know what to do anymore. 
I've bought a cheap Arduino made by "Elegoo". It isn't displayed in SimHub but I can upload sketches in SimHub...
Could there be a problem that the chip for serial communication my Arduino uses is a CH341 and not the same as used in the original? Or has anybody a solution for my Problem?

Thanks
ShootingTiger

**Comment by zegreatclan** [comment]
Hi ! 

It should not be a problem, I use personally a lot of them .
Make sure in simhub "enable arduino display" option is checked, 
Uncheck multiple usb if you don't need it.

If it's not enough a little simhub restart can be helping if somehow the serial port is stuck, eventually unplug replug the device.

Finally check your wiring, some components such as TM1637 when wrongly soldered or not powered enough can trigger instant "no response" situation where SimHub will disconnect and try to find another device.

If it's not helping can you send me he log files available in C:\Program Files (x86)\SimHub\Logs ?

Let me know how it goes,
Nicolas

**Comment by ShootingTiger** [comment]
Thanks for your fast reply. :)

I've done everything you've wrote but still no Hardware is displayed. I don't connected anything to my Arduino Nano except a LED from D13 to GND. 

So I've attached the log files, I took a look but I couldnt find anything. Maybe you have better luck.

Thanks
ShootingTiger
[Log.txt](https://github.com/zegreatclan/AssettoCorsaTools/files/1403606/Log.txt)

**Comment by zegreatclan** [comment]
Hum, it's really strange, the typical log should be showing 
this kind of messages : 
[2017-10-21 01:43:25,806] INFO - Searching for device 

for me it's really pointing out the fact that the arduino is disabled : 

could you cend me snapshot of this screen ?
![image](https://user-images.githubusercontent.com/2207331/31845560-41b1b6aa-b602-11e7-8b57-416eea63e323.png)

I may have an additional idea, did you enable the nextion plugin ? the default comport on it  is COM10 and will prevent any attempt to connect to an arduino on this port. Can you try to disable it if it is enabled ?

**Comment by ShootingTiger** [comment]
A small update: For a short time, it found my Arduino but after i doesnt made what it should made. I've reuploded the sketch and now I can't find it anymore....

I also deactivated Nextion
![unbenannt](https://user-images.githubusercontent.com/32970516/31845758-d859ecd8-b604-11e7-99c0-12424a8f62db.JPG)

**Comment by ShootingTiger** [comment]
Could that be relevant?
[Log2.txt](https://github.com/zegreatclan/AssettoCorsaTools/files/1403639/Log2.txt)

**Comment by zegreatclan** [comment]
Hum, I think I understood a part of your problem, in your snapshot is see that AC is runing (game connected). Could you try first with game is totally not running, simhub should connect to your device.
After you can go ingame (it's not mandatory to proceed in this order but to understand what is going it's important to get things step by step).

**Comment by ShootingTiger** [comment]
Thank you for your help. For some reasons its working now... I've got a new Problem, but i will create a new Thread for it :)

**Comment by zegreatclan** [comment]
Ok :D
