### ISSUE TITLE
Arduino Custom Command help

### ISSUE THREAD

**Issue by ShootingTiger** [zegreatclan/AssettoCorsaTools#154]
Hey Guys,

I want to learn how the connection with SimHub and an Arduino nano works, so I've made a short addition to the predefined sketch. So that on startup a LED lights up, I've uploaded it in SimHub but nothing happens... I've took the modified script and uploaded it via the Arduino IDE and it works. 
So I guess the sketch I'm uploading in SimHub is not the one modified by me... But how do I get SimHub to upload the modified one? (Because otherwise it isn't recognized by SimHub)

Sorry for my bad English,
Thanks
Shooting Tiger

**Comment by zegreatclan** [comment]
Basically when you use the setup tool, it will load the sketch in memory and overwrite it before each upload.  The sketch tool will take care of keeping your modifications as long as they have been made before you start it.

To be sure of the version you're uploading follow the following process :

- Open the sketch setup tool 
- Configure the basic things (such as names or displays if you have some)
- Click on "open with arduino ide" in the tool
- Now you can close the setup tool to make sure any modifications you would do will not get overwritten.
- In the arduino ide you can modify and upload the sketch as you would do with any arduino IDE.

Make sure to close SimHub when your try to upload to your arduino, Simhub is constantly scanning for Comports and would prevent you to upload with the IDE.

In any case make a backup of your sketch, if you update simhub it will get overwritten.

**Comment by ShootingTiger** [comment]
Ok, will try it this way!
But is there a way to monitor the serial Communication between SimHub and Arduino?

Thanks

**Comment by zegreatclan** [comment]
You can use some advanced tools like https://www.eltima.com/products/serial-port-monitor/?gclid=CjwKCAjw4KvPBRBeEiwAIqCB-fJoY0TwcCMXgCEBgd1L2Mto6rCQ_mUuYvEMu8HCh6SjdNUEaKqqcxoCf1oQAvD_BwE

It's a trial but it's really efficient.

**Comment by ShootingTiger** [comment]
Ok thank you alot!! Could solve all of my problems :)
