### ISSUE TITLE
pages using action buttons

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#156]
Hi Wotever,

I've found (on the last few versions, not just v6) that when you have a heavy session opening and closing dashboards the pages you can scroll through start behaving weirdly. They either just stop working, only a couple of them show or they move into different order. A reset of simhub solves it.

**Comment by zegreatclan** [comment]
Hi ! On mobile or WPF ?

**Comment by Meekstaaa** [comment]
on web version second screen. (not mobile)

**Comment by zegreatclan** [comment]
I think I got it I made the events coming from the wpf dash go to the web version, I think it was triggerring twice. I removed the web plugin so the web dash will act exacly as the wpf version.However  I will make further tests
