### ISSUE TITLE
page property visable action

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#157]
Hi again!

I've found when trying to use the visable ncalc on a page (the 'ingame' option) it doesn't appear to work. 

Would be cool if it it shows as false then when scrolling through that page it skips it.

**Comment by zegreatclan** [comment]
In fact I'm not sure of being able to "bind" them, the buttons should not have been visible, the pages are a specific container which is separated of the binding engine

**Comment by Meekstaaa** [comment]
fair enough :)

**Comment by zegreatclan** [comment]
I removed the binding button since it was not applicable
