### ISSUE TITLE
sector times not updating - PCars 2

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#160]
Hey,

Just noticed that the 'newdata' sector times in PCars 2 aren't updating but there is data coming in on the mcurrentsector feed from the game.

Just thought you should be aware :)

**Comment by zegreatclan** [comment]
Thanks ! I will look !

**Comment by zegreatclan** [comment]
LastSectorTime will be fed correctly on next release !
