### ISSUE TITLE
rfactor 2 not recognising LED's

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#162]
Hi Wotever,

Just messing around with RFactor 2 and noticed that my LED layouts arent working even though dash studio is.

My leds are being recognised by simhub and the ncalcs are correct (they work ok on IRacing which uses the same formula's)

Looking through the log it shows that it see's the leds and the game is running ok. Could you have a look at some point please.

Cheers.

**Comment by zegreatclan** [comment]
Are you using some game restrictions or such a thing ?

**Comment by Meekstaaa** [comment]
I am. And I have rfactor2 selected along with rfactor 1 based games. That’s what I thought at first too.

Many thanks

David Meek
Sent from my iPhone

On 31 Oct 2017, at 23:44, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using some game restrictions or such a thing ?

**Comment by zegreatclan** [comment]
Since the latest version you can see the active led mapping indicated by a green bar do you see it as active ? 
![image](https://user-images.githubusercontent.com/2207331/32253962-2d64db6a-be9e-11e7-8429-ac7cb30b7bc1.png)

(Sorry for the question deluge :D) I'm not on my "simhub workspace :D" So i can't test right now :D)

**Comment by Meekstaaa** [comment]
No need to apologise.

I can only see my ‘off’ set of leds selected which doesn’t have any game restrictions on it. Even when I try to scroll through my led sets it won’t move from the off set.

How I have it set:
Everything done twice. Once for assetto and pcars and the others for iracing and rfactor. Then ha e the following led layouts in each set.
1 common set of leds
4 different rpm style leds.

Then there’s a generic off set for when I don’t want to use them. Don’t know if that makes any difference but I can’t see how it would as both sets work fine with their respective games (except this set not liking rfactor but ok with iracing)

Many thanks

David Meek
Sent from my iPhone

On 31 Oct 2017, at 23:47, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Since the latest version you can see the active led mapping indicated by a green bar do you see it as active ?
[image]<https://user-images.githubusercontent.com/2207331/32253962-2d64db6a-be9e-11e7-8429-ac7cb30b7bc1.png>

(Sorry for the question deluge :D) I'm not on my "simhub workspace :D" So i can't test right now :D)

**Comment by zegreatclan** [comment]
Hi ! Indeed the game restriction was guilty, rfactor2 restriction was not recognized, it's fixed :D
