### ISSUE TITLE
TC Active not working on pcars 2

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#163]
Hey,

Just a heads up, the TC active isn't working with the new API. :)

**Comment by Meekstaaa** [comment]
Also sector index's are -1 in pcars 2. Not sure if you saw my update in the other issue thread.

**Comment by Meekstaaa** [comment]
FYI - Had a dig through the api and TC active is no longer supported by pcars 2. :(

**Comment by zegreatclan** [comment]
Shame :( ok so I have to mark it as unsupported a

**Comment by zegreatclan** [comment]
Marked as unsupported for next release .... shame ...
