### ISSUE TITLE
Problem after actvating a bad plugin i made

### ISSUE THREAD

**Issue by Drone45** [zegreatclan/AssettoCorsaTools#167]
i think i just f**ked up my simhub activating a bad plugin i made...
i can't do anthing, i'm stuck in the simhub like loading at the start (but actually not loading) even if i start it again...
![immagine](https://user-images.githubusercontent.com/33610403/32705221-d56cb810-c811-11e7-8d53-8decf0a62b77.png)
[SimHub.log](https://github.com/zegreatclan/AssettoCorsaTools/files/1465252/SimHub.log)

**Comment by Drone45** [comment]
[logs.zip](https://github.com/zegreatclan/AssettoCorsaTools/files/1465254/logs.zip)

**Comment by zegreatclan** [comment]
Hi! Sorry I had to go yesterday,
Go into the settingscontrol.xaml file and remove the line referencing this file :
styles/customizedwindow/vs2012windowstyle.xaml

Recompile and it should go.

It's a line I left on the previous SDK I've already fixed it for next release, but totally forgot about it :(

**Comment by Drone45** [comment]
No problem, it worked thanks a lot!!!
