### ISSUE TITLE
Feature Request: Pit Timer

### ISSUE THREAD

**Issue by garyswallow** [zegreatclan/AssettoCorsaTools#168]
Some form of timer that automatically starts when you enter the pits and stops (then pauses before resetting) when you exit the pit lane.
Timer should be able to be displayed on lcd or 7 segment (Max7221).
Tried doing this with javascript setInterval/clearInterval but neither are defined (although should be in Jint) so the expression fails.
I was using the PCars raw data mPitMode = 1 for entering the pits and mPitMode=3 for exiting.
When stopped in the pits mPitMode = 0 (but it should be 2?). - edit: now mPitMode = 2 when using PCars2 API :)

**Comment by zegreatclan** [comment]
I've added DataCorePlugin.GameData.NewData.IsInPitSince, it starts when you enter in pit lane/pit and resets when you exit.
