### ISSUE TITLE
Feature Request: LED Mapping screen changes

### ISSUE THREAD

**Issue by garyswallow** [zegreatclan/AssettoCorsaTools#169]
To combine mine/Mankiewicz comments from Discord:
Mankiewicz: I'd like an option in the leds presets (where you already have delete, copy, up and down) that place the current layout to the top instead of clicking a lot of times with the arrow. Not a big deal of course, but when you have a lot of leds it's a little bit confusing.

Me: Also can we have an option to name each entry within the led preset so we know what each led function is? They all say RGB LEDS but it would be nice if we could name them eg. RPM LEDS and REV LIMIT FLASH etc.
Once the entry is named could we save each of them individually to a 'library' so we can pick from a list of custom/pre-made mappings to build a new preset? This would save having to create the same mappings within other presets if we want to add more to existing presets.

**Comment by zegreatclan** [comment]
Hi !

This is what i made , each led mapping can be collapsed 
![image](https://user-images.githubusercontent.com/2207331/33780682-e8f61738-dc51-11e7-8812-e356527b57fd.png)

It's now possible to drag'n'drop the entries (insted of the bring to top / down button)
![dragdropledlayouts](https://user-images.githubusercontent.com/2207331/33780753-2c3a88c6-dc52-11e7-8935-d011ba56135d.gif)

It's now possible to add a description for each entry.
