### ISSUE TITLE
simhub changed settings of thrustmaster control panel

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#171]
Just a heads up,

Simhub changed my centering mode when I installed the latest version.

**Comment by zegreatclan** [comment]
Hi ! You mean the game/vs wheel option ? Or the center force ?

**Comment by Meekstaaa** [comment]
Yeah game vs wheel.

Many thanks

David Meek
Sent from my iPhone

On 16 Nov 2017, at 21:50, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi ! You mean the game/vs wheel option ? Or the center force ?

**Comment by Meekstaaa** [comment]
FYI - Noticed everytime you switch between games in simhub it deselects both options which in turn selects 'from the wheel' in the thrustmaster control panel.

**Comment by zegreatclan** [comment]
Indeed there was some weird things
It should be fixed for next release

**Comment by zegreatclan** [comment]
I can't reproduce it anymore since the last fix, i close for now, do not heistate if you still see something weird
