### ISSUE TITLE
Feature Request: Add damage information of rfactor 2

### ISSUE THREAD

**Issue by tafkams1** [zegreatclan/AssettoCorsaTools#176]
No matter if only rawdata or either computed.
You have to look into this:
unsigned char mDentSeverity[8];// dent severity at 8 locations around the car (0=none, 1=some, 2=more)

It's available in the rF2SharedMemoryMapPlugin.

**Comment by zegreatclan** [comment]
Looks like it's a little worthless : https://forum.studio-397.com/index.php?threads/teleminfov01-mdentseverity-meaning-of-each-byte.54338/, i exposed it anyway
