### ISSUE TITLE
Idea - Hide unused dash studio creations

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#177]
Hey wotever,

Had an idea. How about the ability to hide unused dash studio creations? :)

**Comment by zegreatclan** [comment]
Here we go ! I admit it was a mess :D
The behaviour is replicated on web access.

Favourites also place on top your favourites dash 

![hideshowfavs](https://user-images.githubusercontent.com/2207331/33781468-0ed59e30-dc55-11e7-81be-7399eeafeea4.gif)
