### ISSUE TITLE
Idea - For simhub to adjust thrustmaster properties

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#178]
Thinking about this. Thought that what could be a good idea is to have a set of pre-sets loaded into sim hub that adjust depending on what game you have selected. For example RFactor 2 over rides the rotation depending on the car but it then needs to be reset back to max for assetto and pcars.

**Comment by zegreatclan** [comment]
Indeed, it was the logical next step :D, I was thinking to start with something simple with stored profiles, then bind them to a game

**Comment by Meekstaaa** [comment]
Yeah that would be awesome! It would make simhub worth the purchase for people just for that. As it’s similar to Logitech profiler but there is no alternative as far as I’m aware for thrustmaster :)

Many thanks

David Meek
Sent from my iPhone

On 6 Dec 2017, at 16:46, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Indeed, it was the logical next step :D, I was thinking to start with something simple with stored profiles, then bind them to a game
