### ISSUE TITLE
Feature Request: Resizable overlay buttons for little dash

### ISSUE THREAD

**Issue by manuelbiancolilla21** [zegreatclan/AssettoCorsaTools#181]
Really need to implement something to resize the buttons on the overlay for little dash like this: https://i.imgur.com/oas8l9j.png
Look at the top, cannot even make it transparent

**Comment by zegreatclan** [comment]
I've added automatic scaling ;)
![image](https://user-images.githubusercontent.com/2207331/33963666-fbc0ef66-e055-11e7-88ff-96b1da72f3d6.png)
