### ISSUE TITLE
Drivers ahead - behind ehancements

### ISSUE THREAD

**Issue by zegreatclan** [zegreatclan/AssettoCorsaTools#192]
- Add car classes for drivers ahead, behind
- Irating - is it possible to link it to opponents ahead and behind 
- ahead behind opponent - option for race position?
- would be possible to have just surname as option? sometimes is too long

**Comment by hieblmedia** [comment]
- Add current lap count for display and using as detection if a Blue Flag is on opponent or me.

**Comment by BorderlineRacing** [comment]
Could penalties of the cars ahead/behind be added?
