### ISSUE TITLE
Suspect bug in Nextion Plugin

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#197]
have found a suspect bug in the nextion Plugin. I was working with a screen with a lot of variables and I have found that the software seems to ignore the variables when you overcome a certain number.
it is strange because the screen do not updates itself correctly unitil you manually edit the template file
i was working with 16x3 variabiles... as a workaround I had to reduce the number of variabiles to 16x2

**Comment by zegreatclan** [comment]
I close the ticket, any workaround would slow down a lot the screen
