### ISSUE TITLE
Request: Computed Limiter Percent Value

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#199]
The most common use of led strips on real dashboard is as a limiter. Simhub makes easy to use them as RPM indicators but not as limiters. There are a computedRPMpercent but not a computerLimiterPercent.
The "RPM start offset" have no effect on leds or touchscreen bars, so it is useless unless used in a formula.
A proper name for it would be "RPM limiter start".

**Comment by zegreatclan** [comment]
There is a whole new control panel : 
![image](https://user-images.githubusercontent.com/2207331/34457087-d35e7eea-eda6-11e7-8efd-ebc9557719e0.png)

with the related properties : 
![image](https://user-images.githubusercontent.com/2207331/34457090-e540c96a-eda6-11e7-9a57-bfc8fc9edd82.png)
