### ISSUE TITLE
feature request: add fuel consumption needed to finish the race

### ISSUE THREAD

**Issue by manuelbiancolilla21** [zegreatclan/AssettoCorsaTools#201]
add a value that tells you, based on your current fuel level, how much fuel you have to use for each lap to finish the race. preferably that gets updated at the start of every lap, and that doesnt change during the lap

**Comment by zegreatclan** [comment]
Actually you just have to divide the remaining laps (total laps - current lap) by the average consumption. It's very simple maths in this case I think peolple would be more interrested to know how many litrs missing or in excess where you can have a real influence.
