### ISSUE TITLE
BUG: Nextion - goto:screen does not works yet with virtual screens

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#205]
[virtualpages]
screen1=pcmon1
screen2=pcmon4
screen3=pcmon4

[pagesroles]
screen1=skip
screen2=skip
screen3=skip

......
[pcmon.s3]
txt='CPU Volt.'
click=goto:screen3

the result is a jump on the sixth (???) screen and not to the screen3

**Comment by zegreatclan** [comment]
In the wait of a test case
