### ISSUE TITLE
session best data being removed when paused.

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#208]
First off, happy xmas!

Just a heads up, In PCars 2 when you go back to pits via pausing it stops transmitting data (which in itself isn't the end of the world) but when you come out of the pause menu and it starts transmitting it deletes the session best data.

**Comment by zegreatclan** [comment]
Fixed ! The almost invisible black screen when you click on the button was an undocumented game state, it's fixed !
