### ISSUE TITLE
session timer not working - PCars 2

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#209]
As above :)

**Comment by zegreatclan** [comment]
Hum , I took a look but I fear that it's another pc2 regression, everything is plumbed correctly.

**Comment by Meekstaaa** [comment]
That’s strange. At first I thought that too but using crew chief last night he gave me details on how long there is left in the session. Not sure how he’s doing it.

Many thanks

David Meek
Sent from my iPhone

On 24 Dec 2017, at 16:33, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Hum , I took a look but I fear that it's another pc2 regression, everything is plumbed correctly.

**Comment by zegreatclan** [comment]
I will double check, that's why I did not closed the issue :D

**Comment by Meekstaaa** [comment]
👍 hopefully you won’t be checking anytime soon. It’s Xmas!

Have a good one mate.

Many thanks

David Meek
Sent from my iPhone

On 24 Dec 2017, at 16:37, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


I will double check, that's why I did not closed the issue :D

**Comment by zegreatclan** [comment]
Indeed, you were right ! Comments in the api are wrong, it was stated to be in millisesconds, but it was in seconds,
