### ISSUE TITLE
Strong stutter and big slow frames cutts on rF2

### ISSUE THREAD

**Issue by PedroRamada** [zegreatclan/AssettoCorsaTools#210]
Hello 

I've tried and test rFactor 2 Hud - SimHub and even without using the dashboard little window ( because it only gave me slow and delayed info  ) it gave me a lot of delay response time on inputs, on graphics, make my game much more slow! As soon i closed the " available dashboards "   ( the RF2-C1080 - Hud ) and close SimHub also... started the game again and it goes really smooth with no issues at all! I'm talking about actually slow games and slow graphics issues... not the dashboard giving some lag response on info!

Hope you guys can fix this soon because this Tool is amazing and should work in a perfect way! ;) 

Good job and keep it up!! :)

**Comment by zegreatclan** [comment]
Hi ! Could you try to enable the html engine for your dash ? (to access to option click on more on the dash line ). Html engine behaves more consistently in "stressful" situations like full screen overlays.

Full screen overlays are really heavy, and the result will depend of a lot of factors. It's also strongly recommended to enable vsync in the game to allow a decent synchronization between the game rendering and the overlay.

I'm planning to create something in the next week's to get more light overlays. 

I would also think about focus, could it be possible that the game was out of focus after some dash manipulations ?

**Comment by PedroRamada** [comment]
Hey zegreatclan :)

I was using it already yeah... the HTML option... i didin't try yet the v-sync but i doubt it will help tho!

For example yours rF2 Dx11 Iracing Hud - SimHub works perfect... i didin't notice any issues at all.. really... probably because of what you said... the fullscreen overlays are really heavy indeed... i've tried the Overlay triples v1 also and it is the same... even worse on that one! 

Yeah exacly.. i could feel the out of focus yes... completley... and getting worse and worse! 

Thanks for the reply and i really wish that you can find something that really works well for this! 

Great Job man!! :)  i hope for a neww updated version soon :P  ;)

**Comment by zegreatclan** [comment]
Hi ! It took time but the new version had gone out with the promised smaller overlays management, I think I have reached the maximum I can do with this technology, I had pretty good fedbacks on this new working mode,

Let me know how it goes for you.

Nicolas
