### ISSUE TITLE
idea for Arduino Leds

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#213]
An idea for LEDs in arduino. An extra option for RPM leds. Basically instead of using rpm percent have the option for 'percentage under blink trigger ratio' so if you change the BTR the leds stay in the same range.

**Comment by zegreatclan** [comment]
In fact, i'm just on this road, I added per car management of the redline, and i added two shift light level before the redline  managed using percent under the redline, they are "analog" (0 to 1) so it's possible to use it to drive progressively multiple leds 

![image](https://user-images.githubusercontent.com/2207331/34468341-f104652a-ef06-11e7-99c1-4bf3121c0360.png)
