### ISSUE TITLE
bug - latest beta version specific monitor version doesn't work anymore.

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#218]
No matter what screen is selected it just going straight to the main screen.

**Comment by zegreatclan** [comment]
Hum ! I will look at this right now !

**Comment by zegreatclan** [comment]
Fixed for next beta, thanks a lot for the report !

**Comment by Meekstaaa** [comment]
That was quick! Top work man :)

Many thanks

David Meek
Sent from my iPhone

On 18 Jan 2018, at 19:04, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed for next beta, thanks a lot for the report !

**Comment by zegreatclan** [comment]
Just released with b4
