### ISSUE TITLE
Action Buttons

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#225]
Hi Wotever,

Still have issues with action buttons not working. Just had it pretty much stop entirely but the lots show that they are being registered.
[SimHub.log](https://github.com/zegreatclan/AssettoCorsaTools/files/1671487/SimHub.log)

**Comment by Meekstaaa** [comment]
| ERROR | System.IndexOutOfRangeException: Index was outside the bounds of the array.   at PCarsSharedMemory.PC2.PCars2Manager.GetParticipantIndex()   at PCarsSharedMemory.PC2.PCars2Manager.GD_CompletedLaps()   at GameReaderCommon.GameManagerBase`3.PreParseDataBase()   at GameReaderCommon.GameManagerBase`3.PollLoop(Object sender, ElapsedEventArgs e)
-- | -- | --


Also had this pop up, not sure if it's anything to worry about.

**Comment by zegreatclan** [comment]
Ok found it, I think you already gave me the answer in the past, the groups and layers were "cutting" the input message travel in "legacy" mode
