### ISSUE TITLE
Simhub crash

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#226]
Hi,

Again had another crash during a large lobby race. Doesn't look like anything is in the logs. Also the action buttons are still not always reacting despite being registered.

Dash used is linked below:
[McLaren PCU6D - PCars.zip](https://github.com/zegreatclan/AssettoCorsaTools/files/1692173/McLaren.PCU6D.-.PCars.zip)

[SimHub.log](https://github.com/zegreatclan/AssettoCorsaTools/files/1692172/SimHub.log)

Could it be me overloading simhub with everything?

[NCalcScripts.zip](https://github.com/zegreatclan/AssettoCorsaTools/files/1692177/NCalcScripts.zip)

**Comment by zegreatclan** [comment]
Could you send me the events available in the windows event viewer ?

**Comment by Meekstaaa** [comment]
![image](https://user-images.githubusercontent.com/29677438/35771484-6953a04e-0925-11e8-9748-708e029bbda7.png)

**Comment by Meekstaaa** [comment]
Hi,

This has stopped happening since I upped to process priority and now I've got a much better CPU with no bottleneck it's all been fine. I can say you can close this.

**Comment by zegreatclan** [comment]
Nice !
