### ISSUE TITLE
Overlays not working in DiRT rally

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#230]
Not sure if this is SimHub bug or not. When I try to activate overlays in DiRT Rally, the game switches automatically to windowed mode. The only chance to keep the overlays it to use the windowed mode.

**Comment by zegreatclan** [comment]
Overlays only works in windowed (windowed or borderless windowed it doesn't matter), The doc is available here : https://github.com/zegreatclan/AssettoCorsaTools/wiki/Dash-Studio-Overlays
