### ISSUE TITLE
Split Times are not TimeSpans in RBR reader

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#232]
Verified in version 6.3.3
Sorry if already fixed

**Comment by zegreatclan** [comment]
Use these properties, they are cross game : 
![image](https://user-images.githubusercontent.com/2207331/36737543-9a39099c-1bdb-11e8-9ecd-d11a40797e44.png)

raw properties type doesn't have to be consistent, it just keeps as close as the game gives it,  post processing is focused on the normalized data

**Comment by TGD-Simracing** [comment]
Thanks Nicolas 😊


________________________________
Da: Wotever <notifications@github.com>
Inviato: martedì 27 febbraio 2018 16:34
A: zegreatclan/AssettoCorsaTools
Cc: Carlo Iovino; Author
Oggetto: Re: [zegreatclan/AssettoCorsaTools] BUG: Split Times are not TimeSpans in RBR reader (#232)


Use these properties, they are cross game :
[image]<https://user-images.githubusercontent.com/2207331/36737543-9a39099c-1bdb-11e8-9ecd-d11a40797e44.png>

[https://user-images.githubusercontent.com/2207331/36737543-9a39099c-1bdb-11e8-9ecd-d11a40797e44.png]

raw properties type doesn't have to be consistent, it just keeps as close as the game gives it, post processing is focused on the normalized data
