### ISSUE TITLE
BUG: Inconsistent Split Times In RBR

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#233]
<img width="513" alt="issu2" src="https://user-images.githubusercontent.com/28536883/36752380-3844aeda-1c03-11e8-8413-ca95710bfe50.PNG">

The check times are too close to seem realistic

**Comment by TGD-Simracing** [comment]
OK, and it is correct? split times in rally are usually cumulative. I can calculate the sum by myself, not a great problem.

Thanks Nicolas


________________________________
Da: Wotever <notifications@github.com>
Inviato: mercoledì 28 febbraio 2018 08:19
A: zegreatclan/AssettoCorsaTools
Cc: Carlo Iovino; Author
Oggetto: Re: [zegreatclan/AssettoCorsaTools] BUG: Inconsistent Split Times In RBR (#233)


Split time are not cumulated it's the time for the split itself for instance, s2 gives the time for s2 alone, not s1+s2

**Comment by zegreatclan** [comment]
I made an additionnal test this morning everything went fine. I guess the slits are a clean 33%/33% of the track so you get very close times for each split.
