### ISSUE TITLE
BUG: Track Name set to "Unknown" in RBR mods

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#234]
When you use mods the TrackName is always set to Unknown. In these cases the TrackId in the raw game data can be used to identify the track

**Comment by zegreatclan** [comment]
Do you have the RBR tracks.ini file (Maps\Tracks.ini when this happens) ? I tested my mod detection on RSRBR mod, and it gives the correct value, I tried the realrally light but it does not embed any tracks so hard to tell how this mod works, I assumed it would work the same but it looks like I was wrong

**Comment by TGD-Simracing** [comment]
I tested it on realrally


________________________________
Da: Wotever <notifications@github.com>
Inviato: martedì 27 febbraio 2018 22:45
A: zegreatclan/AssettoCorsaTools
Cc: Carlo Iovino; Author
Oggetto: Re: [zegreatclan/AssettoCorsaTools] BUG: Track Name set to "Unknown" in RBR mods (#234)


Do you have the RBR tracks.ini file (Maps\Tracks.ini when this happens) ? I tested my mod detection on RSRBR mod, and it gives the correct value, I tried the realrally light but it does not embed any tracks so hard to tell how this mod works, I assumed it would work the same but it looks like I was wrong

**Comment by zegreatclan** [comment]
And do you have the track.ini and trackid in the rawdata when this happens ? the realrally light does not have any modded track so I cant guess how it works.

In addition I found how car names were stored in real rally  (not like RSRBR) and added a clean support for it.

**Comment by TGD-Simracing** [comment]
Yes unfortunately this behaviour only happens in the complete version.
The only way to test it is to download the complete version.

The complete version requires an account to run, if you need it I can make you have a free account as a developer.
Anyway, i patched the issue by myself. My Navigator does something very close to your map saving. It uses the track names
to associate the navigator logs to the track.

Carlo


________________________________
Da: Wotever <notifications@github.com>
Inviato: mercoledì 28 febbraio 2018 10:57
A: zegreatclan/AssettoCorsaTools
Cc: Carlo Iovino; Author
Oggetto: Re: [zegreatclan/AssettoCorsaTools] BUG: Track Name set to "Unknown" in RBR mods (#234)


And do you have the track.ini and trackid in the rawdata when this happens ? the realrally light does not have any modded track so I cant guess how it works.

In addition I found how car names were stored in real rally (not like RSRBR) and added a clean support for it.
