### ISSUE TITLE
Raw data as object?

### ISSUE THREAD

**Issue by abhibeckert** [zegreatclan/AssettoCorsaTools#236]
When using javascript, is it possible to access DataCorePlugin.GameRawDta.SessionData.Raw as an object instead of an indented string?

I'm currently doing a lot of regex parsing to access fields that aren't otherwise available (eg LastHotPressure for each wheel on iRacing) and it's a waste of CPU cycles.

**Comment by zegreatclan** [comment]
Hi ! 

In fact Iracing is a sneaky game about telemetry, adding and removing data on the fly :D, 
I will look if i can expose each property separately like I do for all the other properties, Giving the full object would be nice for the JS engine however it would be inconsistant for the other engines (ncalc ...)

Nicolas

**Comment by zegreatclan** [comment]
Hi ! I've updated the beta release and i've added all the carsetup related properties to the "raw" properties  : http://www.simhubdash.com/downloads/HubPackage.6.03.8_beta5.zip
![image](https://user-images.githubusercontent.com/2207331/37729889-82a58ec6-2d3e-11e8-9295-cbc258bf7ef2.png)
