### ISSUE TITLE
One Arduino UNO for shake it and Gear indicator display (MAX7221)?

### ISSUE THREAD

**Issue by gegewrc** [zegreatclan/AssettoCorsaTools#238]
Hi!
I'm using an arduino UNO with your "Shake it" sketch in order add simulator Rumble Feedback to my  pedals and it works great.

I'm also interested in adding a Gear indicator to my simrig (with you code for a MAX7221).

Would it be possible to use just one arduino UNO for both functions? If it is possible, which pin number using for connecting the MAX7221 (DATA (DIN), CLOCK(CLK) and LOAD(LD) pins).

Thank you.

Gégé

**Comment by zegreatclan** [comment]
Hi ! it's possible yes, you just need to avoid the pins in use for the boards, all the others can be used :

On motor shield v2 : (https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/faq#faq-10):
```The shield uses the SDA and SCL i2c pins to control DC and stepper motors. On the Arduino UNO these are also known as A4 and A5. On the Mega these are also known as Digital 20 and 21. On the Leonardo these are also known as digital 2 and 3. Do not use those pins on those Arduinos with this shield with anything other than an i2c sensor/driver.```

On DK motor shield (ak motor shield v1) it's a little more complex the doc is here : 
https://learn.adafruit.com/adafruit-motor-shield/faq#faq-12

Just choose free pins depending of your board and it will be ok
