### ISSUE TITLE
Run Once Events

### ISSUE THREAD

**Issue by MorGuux** [zegreatclan/AssettoCorsaTools#239]
A feature that could be added, would be the ability to create events that run once. This could include on game connect/disconnect, engine stalls, etc. An NCalc function could be added that goes true once when a value changes to true, but doesn't run again when that value returns to false.

An example of how this could be used is on the F1 car steering wheels, where if the car is switched off, the LEDs chase from outer to inner edge. https://youtu.be/6sHNqXUZsd8?t=16m31s.

Another example could be when a quick-release mounted steering wheel is attached to a sim, where it could run a test sequence of LEDs and/or dash template, like F1 and GT3 cars. https://youtu.be/QIM2Z-sWwyQ?t=1m28s

**Comment by zegreatclan** [comment]
Hi ! I'm really not convinced it's the way to go, the ncalc functions should as much as possible dependant of temporal things
