### ISSUE TITLE
RRRE - Leaderboard: Wrong opponents after some time in multiclass

### ISSUE THREAD

**Issue by hieblmedia** [zegreatclan/AssettoCorsaTools#240]
Hello,
always on multi class races the leaderboard opponents going wrong after some time. 
Only tested in RaceRoom.
Looks like this happens if the leader is changing from position 1 to 2 and is not yourself.

![screenshot_1](https://user-images.githubusercontent.com/183510/38742505-09824a5a-3f3d-11e8-9c22-862fadf98ccb.png)

![screenshot_2](https://user-images.githubusercontent.com/183510/38742509-0c0c8eca-3f3d-11e8-9922-c07073e6877e.png)
![screenshot_3](https://user-images.githubusercontent.com/183510/38742555-32c5c81a-3f3d-11e8-972b-98a071e7cf62.png)

**Comment by hieblmedia** [comment]
Thanks.
Here are two replay files: https://www.dropbox.com/s/gw6bd9cpj73zzdp/Simhub_RRRE_Replays_Multiclass_Issue.zip?dl=0

Issue is visible just right after starting the replay :D.

**Comment by zegreatclan** [comment]
Thanks for the replay ! It saved me a lot of time :D, it's fixed for the next version !

**Comment by zegreatclan** [comment]
As I said in the other issue the new version on racedepartment should solve it ;) thanks for the feedback by the way, the best way to fix a bug is to know it :D
