### ISSUE TITLE
iRacing Trackmap not work

### ISSUE THREAD

**Issue by hieblmedia** [zegreatclan/AssettoCorsaTools#242]
Hello,
the iRacing Trackmap does not work.
Looks like only 1 of 3 coordinates are implemented in the properties?

Simhub Log:
  | ERROR | Error while loading map
  | ERROR | SimHub.Plugins.MapRenderer.MapException: An error occured while generating map   at SimHub.Plugins.MapRenderer.ImageMapRenderer.GetMap(Double scale)   at SimHub.Plugins.OutputPlugins.GraphicalDash.Models.GeneratedMapItemBase.LoadMap(DataRecordBase record)   at SimHub.Plugins.OutputPlugins.GraphicalDash.Models.GeneratedMapItemBase.UpdateData(GameData& odata)

**Comment by zegreatclan** [comment]
Strange ! I will check that, indeed I racing does not gives the position only percent of the track, an additional process is used to be able to emulate 3d position

**Comment by hieblmedia** [comment]
Ok understand. 
Would be nice to have all coordinates also for the radar item.

Do you need replay files?

**Comment by zegreatclan** [comment]
Hi ! Sorry for the late reply, actually I found the bug, I'm preparing for releasing the update as soon as possible, I hope this week-end.

Iracing does not allows real coordinates, but you can call data.MapResolver.ToAbsoluteCoordinates(data.NewData.CarCoordinates) to map the coordinates in "guessed" real world coordinates. On all games except iracing it will return an identity, and specifically on iracing it returns the coordinates mapped in 2D based on a lap record.

**Comment by zegreatclan** [comment]
Hi ! I published the version to racedepartment, sorry for the delay, this version was so huge I had difficulty to ends all the development faster :D
