### ISSUE TITLE
SimHub (Licensed) Web Dashboard Freezing with ETS2

### ISSUE THREAD

**Issue by SgtBreadStick** [zegreatclan/AssettoCorsaTools#247]
Hey,
I have been using your SimHub dashboard for ETS2, but I have noticed after some time it will freeze and stop doing anything until I refresh it. I changed the ports and quite a lot of stuff and it continues to freeze. I have the Donator's license too. I don't know what would be causing the issue.

Regards,
SgtBreadStick.

**Comment by zegreatclan** [comment]
Hi ! Could you tell me which dash / device and SimHub version you are using ? The web engine is pretty robust and I guess the freeze is triggered by a combination of factors, the more infos you can give the better it will be for troubleshooting ;)

Nicolas

**Comment by zegreatclan** [comment]
Another thing which would help would be to get the log files available here : C:\Program Files (x86)\SimHub\Logs

**Comment by SgtBreadStick** [comment]
Alright, i am using the latest version 6.4.0 Beta 3 on Windows 10 & iPad Mini 2.
I am using the Audio Concept dashboard (modified to match speeds and rpm for ets2)

Here's the latest log
[SimHub.log](https://github.com/zegreatclan/AssettoCorsaTools/files/2042414/SimHub.log)

**Comment by zegreatclan** [comment]
Thanks for the logs, sadly they didn't showed anything strange, however I checked with care the code and I found one weakness which could explain such a thing, I know that the ipad mini 2 due to his retina screen is a slow device and it could eventually render quite slowly compared to how fast simhub can send the data.

I've made you a version with the fix I made, could you test it and tell me if it improves the situation ? https://www.dropbox.com/s/d4qtsem46uqqnn2/HubPackage.6.04.0%20Beta%205_test.zip?dl=0

Nicolas

**Comment by SgtBreadStick** [comment]
Sure, i'll test it as soon as i can :)

**Comment by SgtBreadStick** [comment]
Unfortunately, it still cut out before i even turned on the engine to my truck on ETS2. The iPad Mini hasn't got any problems it runs as fast as possible and does have to odd lag to it but thats wifi. It still cuts out but i guess i'll just keep refreshing it for the time being until a fix has been found. Thanks for the help anyway.

**Comment by zegreatclan** [comment]
Arf, sad, I thought I got it, could you send me your template ? I would like to get as close as possible to the situation you have to test it. Maybe another clue, I know that ETS2/ATS is not really the most CPU saver of the games, could you try to set simhub to higher priority ? (the option is available in the settings)

**Comment by SgtBreadStick** [comment]
I have set SimHub to Highest priorirty (not realtime) as soon as i got it. But the fix you have done has made it cut out even faster and more than before :/

Here's the dashboard i use.
[ETS2Dashboard.zip](https://github.com/zegreatclan/AssettoCorsaTools/files/2058943/ETS2Dashboard.zip)

**Comment by zegreatclan** [comment]
Hi ! Absolutely sorry for this massive delay, I've rewriten the whole enginz since, and did not got any other feedback of such issue, so I guess it was an "environemental issue" (wifi ...)
