### ISSUE TITLE
Statistics issues

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#254]
Hey,

Just a heads up the statistics page on SimHub displays things slightly wrong (Unless it was intended this way).

Assetto Corsa: sector 1 is right, sector 2 is right but sector 3 is sector 1&3 combined:
![image](https://user-images.githubusercontent.com/29677438/41256753-6dfa4074-6dc2-11e8-9405-a87ddfa169cf.png)

PCars 2: sector 1 is right, sector 2 is right but sector 3 is sector 1&3 combined:
![image](https://user-images.githubusercontent.com/29677438/41256637-1e3e0ab6-6dc2-11e8-9b9f-b918570ec675.png)

iRacing doesn't show sectors (assume it can't do that?).
![image](https://user-images.githubusercontent.com/29677438/41256689-467a8d38-6dc2-11e8-9846-97687a8571a7.png)

**Comment by zegreatclan** [comment]
Hum ! Weird I missed it ! concerning Iracing it doesn't gives sectors timing in the telemetry, at best other apps does guessing about it but it's not 100% accurate

**Comment by Meekstaaa** [comment]
Aha! I did wonder if that was a limitation of iracing. Mad they don’t do it.

Sent from my iPhone

On 11 Jun 2018, at 22:02, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


Hum ! Weird I missed it ! concerning Iracing it doesn't gives sectors timing in the telemetry, at best other apps does guessing about it but it's not 100% accurate

**Comment by zegreatclan** [comment]
Actually the reason they "use" is that the server will compute it "later" matching all the data it has to get an accurate timing
