### ISSUE TITLE
REQUEST: Ability to change background screen color on Nextion

### ISSUE THREAD

**Issue by TGD-Simracing** [zegreatclan/AssettoCorsaTools#256]
It would be very nice if you could address the background color on the Nextion.
A lot of real car dashboards use the background screen flashing to signal the shift point.

**Comment by zegreatclan** [comment]
I think it's a bad idea performance wise, at least in this usage. the nextion is a tight performance system, changing the background will force a full redraw with a big impact on performance. however I'm rewriting currently the mapping system to allow the use of an editor so i will integrate it in this new version.

**Comment by zegreatclan** [comment]
I've reviewed the possibility to add it, and I won't do it, it would require to change the backgrounds for all the components too, none of the components have a "transparent background" which makes changing the background totally painful.

**Comment by zegreatclan** [comment]
Pretty ugly ;) 
![image](https://user-images.githubusercontent.com/2207331/42772182-f5e927fc-8929-11e8-916f-60f08fdf174c.png)
