### ISSUE TITLE
Suggestion: More then 6 TM1637 Modules

### ISSUE THREAD

**Issue by Rovexx** [zegreatclan/AssettoCorsaTools#258]
Currently there is a maximum of 6 connected TM1637 modules. I have 8 and I have manualy edited the code to enable 8 modules (very simple). It would be great to have this as standard.

**Comment by zegreatclan** [comment]
Hi ! Indeed there is only a few limitations on computer side, this could be raised. Historically the sketch was not fitting in memory of a 328p. I've used conditional compilation since, allowing to be a bit more large on maximum components
