### ISSUE TITLE
iRacing Leaderboard wrong ordering

### ISSUE THREAD

**Issue by hieblmedia** [zegreatclan/AssettoCorsaTools#259]
Hello,
in iRacing the opponents are not ordered. And not all drivers in Leaderboard available?
Screenshot: http://prntscr.com/k5qzgn
Short replay: https://www.dropbox.com/s/hzmpbvadloj0taj/20180712_205256.telemetry.json?dl=0

**Comment by zegreatclan** [comment]
Hi ! Thanks for the report (and the replay ;) ) I've been able to do a fix, but since i'm currently in holidays i can't try in real conditions, when I get back to home I will do some further testing prior to a release.
