### ISSUE TITLE
Idea - CANBUS Support

### ISSUE THREAD

**Issue by MorGuux** [zegreatclan/AssettoCorsaTools#260]
For CANBUS clusters that are documented, support could be provided with a new user interface that allows for a NCalc (or multiple) to control a message that is sent to the cluster. Option must be included to send repeated data at a certain interval (200ms eg), to avoid data timeouts.

**Comment by zegreatclan** [comment]
I'm sorry as you have seen yourself canbus is really specific to each cluster and can't be really universal.
