### ISSUE TITLE
iRacing - TC switch showing as null

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#261]
Hey,

[DataCorePlugin.GameRawData.Telemetry.TractionControlSwitch] is constantly showing as null. some cars i drive have the override button which I assume is linked to this. Can you check the code when you get a chance. :)

https://drive.google.com/open?id=1l61p_LI-YbymIVsojhlmg3oa_uWZEZaw

**Comment by zegreatclan** [comment]
I've updated the definition of chassis data where the data has been moved in the IR SDK, and as a backcompatibility measure i've fed telemetry with those data.
