### ISSUE TITLE
F1 2018 beta

### ISSUE THREAD

**Issue by manuelbiancolilla21** [zegreatclan/AssettoCorsaTools#264]
Is it possible to release a beta having f1 2018 udp specifications before 20th august? (just asking)
[F1 2018 UDP Specification — Codemasters Forums.pdf](https://github.com/zegreatclan/AssettoCorsaTools/files/2273812/F1.2018.UDP.Specification.Codemasters.Forums.pdf)

**Comment by zegreatclan** [comment]
Considering the changes it's not possible to implement it without having the game in hand. I will start to implement it when it will be released.
