### ISSUE TITLE
Offer: Add support for the Freetronics motor Shield to the DisplayClientV2

### ISSUE THREAD

**Issue by ahuxtable** [zegreatclan/AssettoCorsaTools#265]
I recently got a Freetronics motor shield: https://www.freetronics.com/hbridge and have successfully modified the DisplayClientV2 file to be able to use it with SimHub ShakeIt.

If you want I can give you suitable code to be able to implement it in the main release.

**Comment by zegreatclan** [comment]
Hi ! Compared to the existing hardware supported this board is 4 to 6 times more expensive and can't be found anywhere else then freetronics, I can't even buy one for testing. So it's an extremely bad candidate for out of box support, i'm sorry :(
