### ISSUE TITLE
PCars running on Xbox streaming to PC

### ISSUE THREAD

**Issue by pmajor021** [zegreatclan/AssettoCorsaTools#269]
I try to use PCars on Xbox with SimHub running on a PC which feeds into Arduino. It works well for other games but not for this. I can see with Wireshark the UDP data arriving there, but the app states game disconnected. 

Is it possible to use PCars with SimHub in this way? 

Thanks

**Comment by zegreatclan** [comment]
Hi ! I'm sorry, as shown in the setup intructions for pcars, Simhub needs shared memory for pcars, and gets missing data from UDP. Officially simhub is PC only, even if all the udp only games will work on console too.

This choice on mainly relying on shared memory is driven by the better compatibility accross multiple applications at the same time, it's also more accurate for performances tracking as a simple pause won't be detected as a game disconnect for instance.

**Comment by pmajor021** [comment]
thanks
