### ISSUE TITLE
Front Bias iRacing

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#271]
Hey,

Can you check if this property is working in SimHub? (iRacing)

DataCorePlugin.GameRawData.SessionData.CarSetup.Chassis.Front.FrontBrakeBias

All I get is a null when I think it should work. Some cars Brake bias are set to 0 (Mclaren F1 car and HPD) and I think this should be its default starting value.

**Comment by zegreatclan** [comment]
Actually iracing dynamically feed all these values and it's moving almost for each single car, it's literally impossible to follow :( each time i get a new data sample I can see that the data is moving. 
Concerning the "null" technically it's correct as iracing is not currently feeding this property. Considering the complexity of iracing model i prefer to keep the null as a "non fed" status instead of hiding it under a fake value.

**Comment by Meekstaaa** [comment]
fair enough. :)

I assume there is no way of seeing what the setup has the bias set as then?

**Comment by zegreatclan** [comment]
If you give me a short replay i could browse it and see if there is is not another new "branch" of the car setup i've not discovered yet ;) When using Iracing simhub replays I can rebuild session data even if i've not mapped it yet. Pretty handy when dealing with this iracing telemetry maze

**Comment by Meekstaaa** [comment]
Here you go!
https://drive.google.com/open?id=1m740P6Yi9-OiqVw-NDmbyiSBhsaRWZpK

**Comment by zegreatclan** [comment]
Chassis:
  Front:
   Ballast: -150 mm
   NoseWeight: 45.4%
   BrakePressure: Medium
   **BrakeBias**: 58.0% front

Iracing are you serious ??????

[SessionDataDump.txt](https://github.com/zegreatclan/AssettoCorsaTools/files/2368504/SessionDataDump.txt)

**Comment by Meekstaaa** [comment]
Sounds about right. They mess up so much

**Comment by zegreatclan** [comment]
I think I will transform this to an evolution to "learn" current car setup from iracing as i did in the past for the telemetry part. Otherwise it would be a totally endless race.

**Comment by zegreatclan** [comment]
In another dump it was named frontbrakebias :( the trouble is that now I can't say if it's a renaming or if the name is changing per car

**Comment by Meekstaaa** [comment]
It probably is changing per car. I’ve found a load of strange values with iracing.

Also. That blue flag bug doesn’t appear fixed on last beta. I really need to get a recording for you!

Many thanks

David Meek
Sent from my iPhone

On 10 Sep 2018, at 23:01, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


In another dump it was named frontbrakebias :( the trouble is that now I can't say if it's a renaming or if the name is changing per car

**Comment by Meekstaaa** [comment]
What do you mean by this ‘learn’?

Making simhub automatically read properties?

Many thanks

David Meek
Sent from my iPhone

On 10 Sep 2018, at 22:56, Wotever <notifications@github.com<mailto:notifications@github.com>> wrote:


I think I will transform this to an evolution to "learn" current car setup from iracing as i did in the past for the telemetry part. Otherwise it would be a totally endless race.
