### ISSUE TITLE
Blue Flag issue start of races. iRacing

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#272]
Hi Wotever,

The blue flag at the start is still present :(

Linked is a replay of the start of the race with the blue flag issue.
https://drive.google.com/open?id=13l_VInU8FfbpoYf7r-Dk1wi_RTnEPNgp

**Comment by zegreatclan** [comment]
Thanks for the replay, I confirm nothing is sneaky on simhub side, iracing reports a blue flag in telemetry, I've expanded the "lock" to the first 15 seconds of the first lap, but I won't go further as it could remove legit blue flags.

As you can see iracing sends a blue flag.
![image](https://user-images.githubusercontent.com/2207331/45386264-3551fe80-b613-11e8-9c8e-14340ab5a528.png)

**Comment by zegreatclan** [comment]
Edit I used 20 seconds, but really it's the max I can do.
