### ISSUE TITLE
shake it active on replays

### ISSUE THREAD

**Issue by Meekstaaa** [zegreatclan/AssettoCorsaTools#274]
Hey. 

Just a heads up. I just ran an iRacing replay and the shakeit motor was still running despite having 'active on replays' disabled. 

It's a fanatec brake pedal so not sure if the issue is somewhere there. Was working fine when you first put it in.

**Comment by zegreatclan** [comment]
Indeed pedals were active on replay, from what i see it has never been blocked on this particular device (pedals), but it's fixed ;)
