### ISSUE TITLE
Exported profiles adds random "White Noise" to Bass Shaker settings

### ISSUE THREAD

**Issue by o2dazone** [zegreatclan/AssettoCorsaTools#275]
Not sure what the primary cause is, but it looks like it's taking 'Upper Range' frequencies, and turning them into white noise for exported profiles. Haven't done a ton of testing, but noticed it the two times I've done it so far. I can attempt to replicate if need be.

**Comment by zegreatclan** [comment]
Oh indeed ! I don't know How I missed it Oo, Thanks for the report ! That will be fixed for the next version.
