### ISSUE TITLE
PitEnter and PitOut event Bug and conflit with ACIDLE.

### ISSUE THREAD

**Issue by durstboiler** [zegreatclan/AssettoCorsaTools#35]
En Français sinon je m'en sort pas.

J'ai configuré plusieurs annonces : 
pour PitEnter : 
-3s session
-time session
Il y a seulement time session qui s'affiche.

pour PitOut : 
-3s session
-3s position
-ecran de base
Il y a seulement l'écran de basse qui s'affiche.

Quand je suis dans les pits avec "time session" afficher, je quitte le jeu, il reste afficher alors que ce devrait etre à l'horloge de se mettre.
Je relance un hotlap, toujours le "time session" meme en roulant. il faut que je retourne dans les stands et les quittes pour retrouver mon écran de base.

**Comment by durstboiler** [comment]
J'ai eu aussi un conflit avec des annonce qui ne s'affichaient pas avec "NewValideLap" alors que dans la config de base que tu a paramètrer ça fonctionnait. J'ai réussi à le faire fonctionné je ne sais plus comment. Est ce que l'odre des annonce dans le tableau "screens" a une importance ?

**Comment by zegreatclan** [comment]
L'ordre des annonces à une importance, elles ne sont peux être pas respectées entre plusieurs types d’événements (https://github.com/zegreatclan/AssettoCorsaTools/issues/18) , mais sur un même événement cela marche ;) et en fonction de la conf cela peux totalement changer le comportement ;)

**Comment by zegreatclan** [comment]
Concernant le problème que tu cites, les actions de type "showscreen_xxxx" (sans temps) bloquent l'écran voulu, jusqu’à ce qu'on fasse un next ou un previous. Il sont adaptés à mapping "during" sur un bouton, puisque cela s'affichera jusqu'a ce que l'on relache.

**Comment by zegreatclan** [comment]
En tout cas merci de tous ces feedbacks ;)

**Comment by durstboiler** [comment]
Pour l'odre des annonces je parlais de celle du "tableau" "screens" pas "event mapping".

Pour le cas de mon exemple sur les annonces PitEnter et PitOut, les annonces avec 3s placer avant ne devraient elles pas s'afficher ?

**Comment by zegreatclan** [comment]
L'ordre dans la configuration des screens n'est important que pour les
next/preview, mais ne joue pas du tout lors des mappings, seul l'ordre des
mappings est important.

Le 29 mai 2015 15:17, durstboiler <notifications@github.com> a écrit :

> Pour l'odre des annonces je parlais de celle du "tableau" "screens" pas
> "event mapping".
>
> Pour le cas de mon exemple sur les annonces PitEnter et PitOut, les
> annonces avec 3s placer avant ne devraient elles pas s'afficher ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zegreatclan/AssettoCorsaTools/issues/35#issuecomment-106800064>
> .
>



-- 
Nicolas GUILBERT
Adresse : 80 rue Henri Briffaut
59150 Wattrelos
Email : nguilb@gmail.com
Portable : 06 79 16 34 34
