### ISSUE TITLE
The screen clock display remains in race mode.

### ISSUE THREAD

**Issue by durstboiler** [zegreatclan/AssettoCorsaTools#54]
In the ac menu, the clock is displayed, but when I start a "mode race", the display does not switch to "main screen" but remains on the clock.

**Comment by JoshuaxCZ** [comment]
This is working well for me.

**Comment by durstboiler** [comment]
I have tested stock 1.6 and it work, but, if i delete the "welcom" screen, don't work.

**Comment by durstboiler** [comment]
Finally, it worked juste one once, don't work again despite the "welcom" screen...

**Comment by zegreatclan** [comment]
Probaably related to #63
