### ISSUE TITLE
Dashboard screen deletion/ordering (Dash Designer)

### ISSUE THREAD

**Issue by BuToNz** [zegreatclan/AssettoCorsaTools#68]
Unable to order dashboard screens and delete them, add ability to rename them.

**Comment by zegreatclan** [comment]
Renaming is possible from the component list : 
![image](https://cloud.githubusercontent.com/assets/2207331/24374895/cbf29114-1336-11e7-9c21-5c57950532ac.png)

But I will add it to the scren list ;)

**Comment by zegreatclan** [comment]
You can now reorder with drag'n'drop, right click allows to delete screen
